// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { nativeAuthStorage } from '@/lib/nativeAuthStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Native builds store the session in Capacitor Preferences (never
    // evicted by iOS, unlike WKWebView localStorage) with one-time
    // migration from localStorage; web builds keep using localStorage.
    storage: nativeAuthStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});